build.boot, resources/grammar/alda.bnf, src/alda/parser.clj, test/examples/awobmolg.alda
Allow optional slurs at the end of notes and durations.
=> Ties and slurs

src/alda/cli.clj
Fixes #25. (The boot-related issue I was running into before has been fixed upstream.)
=> Pretty-print output of 'alda parse' task

src/alda/cli.clj
Currently when the parser fails, it exits with a success code.  This fixes that using `instaparse`'s `failure?` function.  Exiting with an error code here would allow better support for [atom-build](https://github.com/noseglid/atom-build) and could even move the user's cursor to the error in the file (with the help of a regex).
I don't have much experience with clojure, so let me know if there's a more idiomatic way of doing this.
=> Exit with error code when parser fails

src/alda/lisp/attributes.clj
=> Remove 100% constraint on quantization

src/alda/repl.clj, src/alda/repl/commands.clj, src/alda/repl/core.clj
Just hacked this in, after realising it wasn't there and really wanting it :tropical_drink:
=> Add :play command to play currently loaded score

build.boot, test/alda/helpers.clj, test/alda/lisp/attributes_test.clj, test/alda/lisp/chords_test.clj, test/alda/lisp/duration_test.clj, test/alda/lisp/global_attributes_test.clj, test/alda/lisp/markers_test.clj, test/alda/lisp/notes_test.clj, test/alda/lisp/parts_test.clj, test/alda/lisp/pitch_test.clj, test/alda/lisp/score_test.clj, test/alda/lisp/voices_test.clj, test/alda/parser/attributes_test.clj, test/alda/parser/comments_test.clj, test/alda/parser/duration_test.clj, test/alda/parser/events_test.clj, test/alda/parser/score_test.clj, test/alda/test_helpers.clj
Decided to just knock this off while adding a test for the quantization
=> Test reorganisation

doc/attributes.md, src/alda/lisp/events/note.clj, src/alda/sound/midi.clj, test/examples/panning.alda
=> Implement panning

build.boot, doc/installation.md, grammar/alda.bnf, src/alda/cli.clj, src/alda/parser.clj
=> `alda script` task

client/src/alda/AldaServer.java, client/src/alda/Client.java, server/src/alda/server.clj
=> alda load command; awareness of file changes

client/src/alda/AldaServer.java, client/src/alda/AldaServerInfo.java, client/src/alda/Client.java, client/src/alda/Util.java
Closes #157.
(opting not to do the `:edit` Alda REPL command right now -- it would involve teaching the REPL how to interact with an Alda server, which depends on #154)
=> alda edit command

build.boot, client/src/alda/AldaServer.java, client/src/alda/Client.java, client/src/alda/Util.java
Closes #161.
Only Mac/Linux supported so far, as I don't have a reliable way to test listing processes in a Windows environment.
=> `alda list` command

client/src/alda/Util.java
The default action is  n(o). Resolves issue #188.
=> Change the update prompt

server/src/alda/lisp/attributes.clj, server/src/alda/lisp/model/duration.clj
Closes #195
Adds a bunch of validations for a couple functions. I think I've got the desired behavior except for `(duration #)`. For some reason, the assertion only works on `(set-duration #)`, and everything I tried to rename it to duration (and alias to set-duration) dosen't seem to work. I'm hoping you'll be able to figure out what I'm doing wrong there. Seems like things like `a-1` still work, but `a0` is caught. 
Let me know if I'm doing anything wrong, this is my first time writing clojure :smiley:
=> Add a slew of validations.

server/src/alda/server.clj, server/src/alda/worker.clj
=> Detect suspension, cycle workers

scripts/jeromq-sanity-check-client-ctx.boot, scripts/jeromq-sanity-check-client-zcontext.boot, scripts/jeromq-sanity-check-server-ctx.boot, scripts/jeromq-sanity-check-server-zcontext.boot
Update the example output to match the new file names.
=> update sanity-check example output

doc/alda-now.md
Seem to be an extra "alda" in the name here, I had to remove it to get it to work in my project.clj
=> Fix requirements names

README.md
Added server start step to Demo section
=> Update README.md - Added server start step to Demo section

README.md
- capitalize "Control Panel"
- indent JDK 8 note under list item #1
=> change capitalization and indentation in README.md

doc/community.md, doc/index.md
Fixes https://github.com/alda-lang/alda.io/issues/17
- Add **Community** page under `Useful Links` list
=> Add community documentation

README.md
After [this PR](https://github.com/NixOS/nixpkgs/pull/91176), nix users can install alda :)
Thanks for the awesome project.
=> Add Nix installation to README

examples/rachmaninoff_piano_concerto_2_mvmt_2.alda
Let me know if you want me to update the formatting or anything
=> Adding Rachmaninoff excerpt as new Alda example file

CONTRIBUTING.md
I've been poking around the project and saw that this page did not reflect the changes to the project, so I added a notice at the top to hopefully make the changes clear to any newcomers who shoot straight to the Contributing page.
=> Added notice about current changes to repositories

CONTRIBUTING.md, player/README.md
=> :memo: Updated OSC links

client/interop/musicxml/importer/importer.go
I took a look at general code organization within Alda, and made some changes in the importer to better follow convention: 
1. Even ridiculously simple comments should be added for important public methods. e.x. for `ParseFile` or `ScanFile`. This is for organization, but also to auto-generate docs. I've added comments to `ImportMusicXML`.
2. The public method should be at the bottom of the file. I've adjusted `ImportMusicXML` to the bottom. 
3. Multiplexed methods like importer handlers, scanner `parseOctaveSet` / `parseString`, etc. should be methods on the struct itself. So like `scanner.parseString` instead of `parseString(... s *scanner)`. I didn't change this one within the MusicXML importer because it's just way too complex to put the handlers in the same file. 
Btw the diff on …
=> MusicXML Importer - Reorganization

client/model/lisp.go, client/model/notes_test.go
Hi Dave, 
We have added pause functionality to the Alda client and have provided some test cases. Let me know if you have any questions or concerns about the code.
Best,
Justin
=> Added pause functionality for request #382

client/interop/musicxml/importer/handlers.go, client/interop/musicxml/importer/importer.go, client/interop/musicxml/importer/util.go
Had some more time to do some smoke testing, so fixed two more things. See commits.
Can just merge.
=> Miscellaneous MusicXML Bugs
