alda-lang/alda

resources/grammar/alda.bnf
src/alda/lisp.clj
src/alda/parser.clj

Instaparse now transforms each instrument part's parse tree (Hiccup) into Clojure code that can be eval'd. Each event type will be its own function -- most of these still need to be implemented, but the structure is in place, and it feels good.

Lispify Alda

---

README.md
build.boot
src/alda/cli.clj
src/alda/now.clj

This PR turns off debug-level logging when using Alda either from `alda.cli` (i.e. the `bin/alda` script) or `alda.now`. The default log level is now `warn`, so users will still see warnings and errors.
The default log level for running tests via `boot test` is still `debug`.
In all scenarios, the log level can be overridden by setting the `TIMBRE_LEVEL` environment variable.

Make 'warn' the default log level in production

---

src/alda/repl.clj
src/alda/repl/commands.clj

3 new REPL commands:
`:load <filename>` loads an Alda score from a file. Prompts for confirmation that you want to abandon your current score if the current score is "dirty" (this needs to be improved -- right now it assumes the score is "dirty" if it's not empty)
`:map` pretty-prints the current data state of the score, i.e. the result of evaluating `(alda.lisp/score-map)`
`:score` prints out the current score-in-progress, as Alda code.
Incidentally, refactored a little bit in the alda.repl.commands namespace, and included the REPL ConsoleReader as an argument so that REPL commands can do things like `.readLine` on it.

[repl] :load, :map and :score commands

---

build.boot
grammar/alda.bnf
src/alda/lisp/events/barline.clj
src/alda/parser.clj
src/alda/version.clj
test/alda/parser/barlines_test.clj
test/alda/test_helpers.clj

This is a change that will help facilitate visually rendering scores. Bar lines are now parsed as a [:barline] node, which is transformed to a call to (alda.lisp/barline), which does NOTHING. IT DOES ABSOLUTELY NOTHING.

Include bar-lines in the parse tree

---

grammar/alda.bnf
src/alda/cli.clj
src/alda/lisp/model/duration.clj
src/alda/version.clj
test/alda/lisp/duration_test.clj
test/alda/parser/barlines_test.clj

Fixes #97.
Incidentally, this PR also adds a `--tree` flag to the `alda parse` task, which prints the intermediate AST when set.

Allow tying across barlines

---

grammar/alda.bnf
src/alda/parser.clj
test/alda/parser/clj_exprs_test.clj

Looks like it works, but perhaps too naive? Certainly seems simpler :wink: 
Watch out, this contains #105. For a clean diff just look at e41ca1c8c7473052e2eaeb90a2b2492dc28b461e

Simplify CLJ expression parser

---

grammar/alda.bnf
src/alda/parser.clj
test/alda/parser/clj_exprs_test.clj

There were two issues I found - one serious, and one perhaps debatably an issue.
1. Expressions may be expanded with terms in the wrong order
2. Nested expressions can also be exploded - IMHO this is not worth possible confusion with return value of expression or usage with lists.
I've provided crude fixes for these issues in subsequent commits.
After having a bite to eat I'm going to see if we can simply `read-clj-expr` too - my hunch is this will become a bottleneck in larger scores (esp. machine generated ones, being reprocessed inside a bigger score by `alda.lisp/alda-code`)

Fix issues around clj-expr parsing

---

doc/attributes.md
doc/index.md
doc/inline-clojure-code.md
doc/notes.md
grammar/alda.bnf
src/alda/lisp/attributes.clj
src/alda/lisp/events/note.clj
src/alda/lisp/model/key.clj
src/alda/lisp/model/pitch.clj
src/alda/parser.clj
test/alda/lisp/global_attributes_test.clj
test/alda/lisp/notes_test.clj
test/alda/lisp/pitch_test.clj
test/examples/key_signature.alda

Closes #36.
This is an iteration on PR #89 started by @FragLegs. After just a few tweaks, it's working great! Not having to worry about the parsing step due to #94 is a big win.
TODO:

Key signatures

---

CHANGELOG.md
bin/alda
build.boot
grammar/alda.bnf
src/alda/parser.clj
test/alda/parser/clj_exprs_test.clj

Simplify inline Clojure code

---

build.boot
src/alda/cli.clj
src/alda/lisp/score.clj
src/alda/now.clj
src/alda/repl/commands.clj
src/alda/repl/core.clj
src/alda/sound.clj
src/alda/util.clj
test/alda/util_test.clj

Not quite done with this yet, but perhaps ready for feedback.
There are some performance-oriented things here, like making some functions lazy, a lower-overhead trick than `(doall (pmap ..))` and using transducers in some places.
Will be back this evening to finish this off - supporting labels, typing in with CLI and REPL commands, and adding tests

Support "from" and "to" for playing

---

README.md
build.boot
doc/inline-clojure-code.md
grammar/alda.bnf
src/alda/lisp.clj
src/alda/lisp/code.clj
src/alda/parser.clj
src/alda/parser_util.clj
src/alda/repl/core.clj
test/alda/lisp/attributes_test.clj
test/alda/parser/barlines_test.clj
test/alda/parser/clj_exprs_test.clj
test/alda/parser/code_blocks_test.clj

This PR implements the `alda-code` function discussed in #104, as well as code block literals, as a stepping stone to implementing repeats (#7).
Code blocks are captured in the grammar as anything between `[ square brackets ]`. At the moment, they are essentially ignored when the score is evaluated -- they simply evaluate to strings. 
I plan to implement repeats as an alda.lisp function `repeat-code` that will take a string of text, repeat it a given number of times, and evaluate it using `alda-code`. There will be some syntactic sugar in the form of `xN` (where `N` is the number of times to repeat) and/or `||:  code here  :||N` which will be parsed as a call to `repeat-code`.

Code block literals and the "alda-code" function

---

build.boot
doc/cram.md
src/alda/lisp/events/chord.clj
src/alda/lisp/events/cram.clj
src/alda/lisp/events/note.clj
src/alda/lisp/events/rest.clj
src/alda/lisp/model/attribute.clj
src/alda/lisp/model/duration.clj
src/alda/lisp/model/offset.clj
src/alda/lisp/score.clj
src/alda/util.clj
test/alda/lisp/cram_test.clj
test/alda/lisp/notes_test.clj
test/alda/parser/events_test.clj
test/alda/test_helpers.clj
test/examples/poly.alda

Fixes #124 (bug w/ nested crams), but unfortunately not #123 (improve cram perf), even though that's what I set out to do on this branch :persevere: 
The original idea I had was that we could gain some perf by not dry-running the entire body in the `cram` macro just to get the duration, resetting everything and then evaluating it for real. This PR takes some of the work out of the initial dry-run -- I added a `*beats-tally*` dynamic var, along with logic in the `note`, `pause` and `chord` events that looks at whether or not `*beats-tally*` is nil, and acts accordingly, either doing what it normally does, or short-circuiting and just adding to the beats tally. The adjusted implementation of the `cram` macro turns `*beats-tally*` on (setting it to 0), sets the duration to 1, tallies up the …

Adjusted CRAM implementation

---

doc/alda-repl.md
src/alda/repl.clj
src/alda/repl/commands.clj

Closes #66.
This PR adds a rudimentary help system that dynamically uses information from the docstrings of the REPL commands defined in `alda.repl.commands`.
`:help` prints a list of available commands, with the first line of each docstring as a brief description of what the command does. 
`:help <command>` prints the full docstring of a command.

REPL help system

---

doc/inline-clojure-code.md
src/alda/lisp/events.clj
src/alda/lisp/events/fn.clj
src/alda/lisp/model/event.clj
src/alda/sound.clj
test/examples/printing.alda

Closes #104.
This adds a "function" event type, which can be scheduled in a similar way to note events via the `alda.lisp/schedule` function.
I'm half-wondering if maybe it should be implemented as a macro instead, so that it can be used in a slightly cleaner way, i.e. `(schedule (println "hi!"))` instead of `(schedule #(println "hi!"))`, but I'm leaning toward it being a function, for the sake of simplicity, and in case we may want to add optional arguments of some kind in the future. Totally open to discussion, though.

Schedule custom events

---

build.boot
client/src/alda/AldaServer.java
client/src/alda/Client.java
server/src/alda/server.clj

Closes #155.
* Adds `filename` atom in `alda.server` which the server can get and set
* TODO: handle this more elegantly (see comments in alda.server)
* Show score info when you GET /
* server status ("up")
* server version
* filename (may be nil)
* line count
* character count
* list of instruments used in score
* e.g.
({:name "piano-9nt5h", :stock "midi-acoustic-grand-piano"}
{:name "cello-Fe3bJ", :stock "midi-cello"})
* `alda info` command prints this info in a user-friendly way

alda info command / server filename

---

build.boot
client/src/alda/AldaServer.java
client/src/alda/Client.java
client/src/alda/UnsavedChangesException.java
client/src/alda/Util.java
server/src/alda/server.clj
server/src/alda/util.clj

Closes #152.
- By default, the server will return 409 if it receives any request asking it to discard unsaved changes.
- For now, "unsaved changes" is naïvely defined as the score being non-empty. (Will implement the file-checking behavior (i.e. if the score was loaded from (or saved to) a file, is the score in memory any different from what's in the file?) very soon along with the `alda save` and `alda load` commands.)
- Re-submitting the request with the `X-Alda-Confirm` header set to anything except for "", "no" or "false" will force the action to take place.
- When the client gets a 409, it warns the user that this action will result in unsaved changes being lost, and prompts for confirmation.
- Also added `-y`/`--yes` options for each relevant command. When this flag is included, the …

Prompt for confirmation before discarding unsaved changes

---

client/src/alda/AldaServer.java
client/src/alda/Client.java
server/src/alda/server.clj

Closes #156.
Foregoing the Alda REPL `:save` command for the time being, as it depends on #154.

`alda save` command

---

build.boot

Closes #171 
`boot build` will now build uberjars (and therefore binaries) that are compatible with JDK 1.7+, making it so that people with older Java versions can use Alda.
I tried going back to JDK 1.6, but there are a couple incompatible things in the Java client source that would need to be resolved, and I'm not sure if it's worth the effort at this point, with JDK 1.6 on its way out. We can always revisit in the future if there is a need for Java 6 compatibility.
Blockers for Java 6 compatibility:
1) The switch statement in Client.java operates on strings, which is not supported in Java 6. We could just make it a series of if/else if statements.
2) The use of `.inheritIO()` in Util.java here:
public static void runProgramInFg(String... args)
throws IOException, InterruptedException { …

Build uberjar with JDK 1.7 support

---

examples/percussion.alda
server/src/alda/lisp/instruments/midi.clj
server/src/alda/sound/midi.clj
server/test/alda/parser/examples_test.clj

Closes #99.
In the future, we will hopefully have a plug-in that will make writing percussion parts much nicer. Perhaps the plug-in could map ASCII characters to different percussion sounds, and then you could write your percussion parts using a drum tab-like syntax.
For now, we can at least make percussion available, and it can be used just like any other MIDI instrument.

Add MIDI percussion instrument

---

server/grammar/events.bnf
server/grammar/voices.bnf
server/test/alda/parser/events_test.clj

In some cases, voice parsing wasn't happening correctly -- subsequent voices were being nested inside of the previous voice, instead of them all being nested at the same level in the voice group like they should be. This was caused by an ambiguous grammar rule that allowed a voice group to be an event in a voice. Alda doesn't support nesting voices inside of voices, so we can solve the ambiguity by disallowing that explicitly.

bugfix re: voice parsing

---

client/src/alda/Client.java

This adds command specific help. Due to JCommander shadowing the original command class there wasn't an entirely acceptable solution, so I took the straightforward route. Commands inherit help behavior from a base class and we check for help in the big switch statement in main(). 
It's not quite as succinct as I'd like but it works.

Adds Command Specific Help

---

README.md

fixes #217 
I've updated the README.md with instructions on how to manually "install" the `alda.exe` program following standard Windows conventions, although I am assuming it's a 32 bit, rather than a 64 bit executable. If it's 64 bit then it'll have to go into `Program Files`, not `Program Files (x86)`

Updated the Windows installation instructions

---

CONTRIBUTING.md
build.boot
client/src/alda/Client.java
doc/development-guide.md
server/test/alda/examples_test.clj

* Whereas before, `boot dev` started an Alda server, now the `-a/--app` argument can be used to run an Alda REPL, server, or client based on the current code with any local changes, without having to build the whole project. This should make it quicker and easier to test changes.
`boot dev -a server --port 12345 --alda-fingerprint` starts a server
(or just `boot dev --port 12345 --alda-fingerprint`; server is the default)
`boot dev -a repl` starts an Alda REPL
`boot dev -a client -x "cli args here"` runs the Alda client with any local changes.
e.g. `boot dev -a client -x "play --file /path/to/file.alda"` is like running `alda play --file /path/to/file.alda`
* Improved documentation about `boot build` and `boot dev` -- hopefully this will make it a bit easier to get up and running for new …

Misc. dev setup improvements

---

doc/windows-troubleshooting.md

What to do when Java's registry entries don't have a `Prefs` key set up.
fixes #224

windows troubleshooting

---

scripts/install-fluidr3

Providing a PR to resolve [issue 232](https://github.com/alda-lang/alda/issues/232) — that the FluidR3 script will fail if the `~/gervill`directory is missing.
(Please let me know if you need any amends)

#232 Updating installation script to resolve missing Gervill directory

---

build.boot
server/grammar/comments.bnf
server/grammar/duration.bnf
server/grammar/score.bnf
server/src/alda/lisp/events/note.clj
server/src/alda/lisp/model/duration.clj
server/test/alda/lisp/duration_test.clj
server/test/alda/lisp/notes_test.clj

I made a pass through each of Alda's parsers with `instaparse.core/parses` to determine whether there was any ambiguity contributing to slow parse times noted in #208. I did find a few places where there was ambiguity in the grammar -- see the commit messages for more details.
Unfortunately, this is only a minor improvement over what we have now. The major example of a slow-parsing score we have now is the Bach cello suite example. Currently on my computer, that score takes about 800-900 ms to parse. With the improvements on this branch, it takes about 700-800 ms which is barely a difference.
I think the next step is going to be considering some of the other suggestions in the [instaparse wiki's performance tips](https://github.com/Engelberg/instaparse/blob/master/docs/Performance.md#perfo …

Parser optimizations

---

build.boot

Empirically G1 was found to put the least load on the system on the three boxes tested.
Memory usage between 250m and 800m.
CPU usage hovers around 9% of one core on my test machines VS 30 with previous values.

#269 Use G1 and add basic memory limits

---

client/src/alda/AldaServer.java

This is for [Issue 242](https://github.com/alda-lang/alda/issues/242). It looks like there were only two actual uses of the `...args` for message formatting, so I just called `String.format` outside `msg` and then removed the extra arguments entirely. It seemed pretty simple, so I may be missing some context here!

Issue 242: Remove variadic args to .msg method and replace printf with println

---

server/grammar/voices.bnf
server/src/alda/lisp/events/sequence.clj
server/src/alda/lisp/events/voice.clj
server/test/alda/lisp/voices_test.clj
server/test/alda/parser/event_sequences_test.clj

I don't have much Alda knowledge, so I've probably missed some use cases. However, this at least tackles the specific problem cases in issue [255](https://github.com/alda-lang/alda/issues/255). It makes two changes that are kind of related, but wouldn't strictly have to be part of the same PR if one of them doesn't check out.
1. Use lookahead to allow an unclosed voice group to parse as part of an event sequence. This addresses the parse error caused by `piano: [V1: c d e V2: e f g]*2`.
2. Unconditionally close any `:event-sequence` (including variable defs) with an `:end-voice-group`. This allows `foo = V1: c d e V2: e f g` to be multiplied by `foo*2`. From a design standpoint, though, I'm not sure if you want this behavior so broadly. The comments on the issue implied that maybe you do, …

255: Implicit Voice Group Closing

---

doc/windows-troubleshooting.md

Describe how to start workers manually if they are not automatically
started on Windows.
Thought these instructions might be useful.

Documentation for worker workaround on Windows

---

client/model/attributes.go
client/model/attributes_test.go
client/model/lisp.go
client/model/part.go
client/parser/lisp_test.go
doc/alda-2-migration-guide.md
doc/attributes.md
examples/bach_cello_suite_no_1.alda
examples/debussy_quartet.alda
examples/dynamics.alda
examples/rachmaninoff_piano_concerto_2_mvmt_2.alda

Alda supports volume setting via `(vol __)` and `(vol! __)` attribute updates. Many scores do not necessarily have numeric volumes, but instead have dynamic markings. This PR introduces basic dynamic markings into Alda via Lisp attribute updates. 
This PR will introduce the `(mf)` and `(mp)` dynamic markings, as well as the `(pppppp)`, ..., `(p)` and `(ffffff)`, ..., `(f)` markings. We choose to support up to 6 pianos or fortes following the MusicXML standard [here](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/dynamics/). 
This PR does not add support for more complex dynamics such as fortepiano or sforzando. We believe this would add unnecessary complication into the Alda language. 
A MIDI note's volume is represented by velocity which is an integer in the range `[0, …

Add support for dynamic markings 

---

client/interop/musicxml/importer/importer_test.go

I've reformatted the MusicXML importer test case file `importer_test.go`. 
1. I realize for some reason I implemented an `executeImporterTestCases` method taking in a varargs `...importerTestCase` parameter but I never used this feature. I've changed to use this for repeated tests like for repeat1, repeat2, repeat3. 
2. I indented all Alda code blocks. This just fits better, especially with the use of varags above. 
This is a simple change. As with before, feel free to just merge PRs like this.

MusicXML Importer - Test Case Reformatting

---

client/repl/client.go

Hello Dave,
I added the ":parts" command mentioned within the REPL feature suggestions of issue #348. 
I referenced other repl command handlers, especially that for ":score," to safely parse the score data and access the map of instruments. 
Please let me know if there are any changes you would like to see (or anywhere that I can add tests). 
I also wanted to ask about the grouping of instruments; as of now, the command simply prints out all instruments within the current score, but the original description mentions a format that 'shows if the instruments are in a group'.

Issue #348 - :parts

---

doc/alda-repl-server-api.adoc

I have noticed that the `describe` operation is not included in the REPL server doc. Any reasons for not adding it?

Add `describe` operation to REPL server doc

---

client/model/note.go
client/model/notes_test.go

Added an error when MIDI is out of the range 0-127 and added a test case checking the error is thrown.

Fix issue #321 - Validate MIDI Note range

---

client/doc/notes/interaction-modes.adoc
client/model/key.go
client/parser/ast.go
client/parser/barlines_test.go
client/parser/chords_test.go
client/parser/comments_test.go
client/parser/cram_test.go
client/parser/duration_test.go
client/parser/event_sequences_test.go
client/parser/examples_test.go
client/parser/gen.go
client/parser/lisp_test.go
client/parser/markers_test.go
client/parser/notes_test.go
client/parser/octaves_test.go
client/parser/parser.go
client/parser/parts_test.go
client/parser/repeats_test.go
client/parser/test_helper.go
client/parser/variables_test.go
client/parser/voices_test.go

Currently for MusicXML import, we are able to go from MusicXML to Alda `[]ScoreUpdate`. The following 3 PRs combined will introduce an Alda code generator to complete the import process:
1. https://github.com/alda-lang/alda/pull/471
2. https://github.com/alda-lang/alda/pull/474
3. https://github.com/alda-lang/alda/pull/475
This PR is the first step of the process, introducing `[]ScoreUpdate` -> `ASTNode` conversion via the following function in `parser/gen.go`:
```
func GenerateASTFromScoreUpdates(updates []model.ScoreUpdate) (ASTNode, error)
```
The generation is mostly straightforward, with a few points to note:
1. As commented, `AldaSourceContext` is ignored in generation. I think this is a very fine choice.
2. Processing parts and voices is a little non-trivial. I tried to do it in …

ASTNode Generation from []ScoreUpdate's

---

client/cmd/format.go
client/cmd/root.go
client/model/duration.go
client/parser/ast.go
client/parser/duration_test.go
client/parser/event_sequences_test.go
client/parser/format.go
client/parser/gen.go
client/parser/parser.go
client/parser/scanner.go
client/parser/test_helper.go

Currently for MusicXML import, we are able to go from MusicXML to Alda `[]ScoreUpdate`. The following 3 PRs combined will introduce an Alda code generator to complete the import process:
1. https://github.com/alda-lang/alda/pull/471
2. https://github.com/alda-lang/alda/pull/474
3. https://github.com/alda-lang/alda/pull/475
This PR introduces a code formatter, translating `ASTNode` to Alda code.
```
func FormatASTToCode(root ASTNode, out io.Writer, opts ...formatterOption) error {
```
The formatter is quite rudimentary, but has basic handling of whitespacing (indents, spaces, line wrapping) while maintaining the integrity of the generated code.
- For indents, we essentially maintain an indentation level. Within parts, voices, and event seqs, we indent.
- For wrapping, we format "texts" or …

Alda Code Formatter

---

client/cmd/doctor.go
client/cmd/export.go
client/cmd/telemetry.go
client/cmd/update.go
client/gen/version/main.go
client/parser/examples_test.go
client/parser/parser.go
client/parser/scanner.go
client/repl/client.go
client/repl/server.go
client/system/dirs.go
client/system/stdin.go

io/ioutil has been deprecated since Go 1.16
https://pkg.go.dev/io/ioutil

refactor: remove io/ioutil

---

client/color/color.go
client/color/color_widows.go
client/color/color_windows.go
client/go.mod
client/go.sum

Fixed one of bugs mentioned in [this](https://github.com/alda-lang/alda/issues/405#issue-1033159114) issue

PS color output fix

---

client/model/repeat.go
client/model/repeats_test.go

This should fix #401.
I have taken different approach than suggested, as it was more time efficient and less error-prone than trying to handle it from outside. Allocating a small array per repeat should not affect performance in any noticeable way.

Nested repeat fix
